### ISSUE TITLE
[ProGuard] ActionBarSherlockCompat: can't find referenced class com.actionbarsherlock.BuildConfig

### ISSUE THREAD

**Issue by rfgamaral** [JakeWharton/ActionBarSherlock#1001]
I'm having an issue with the .aar file and so far it seems I'm the only one. Compiling my app with assembleRelease and using ProGuard I get the following warning which stops the build process:

Warning: com.actionbarsherlock.internal.ActionBarSherlockCompat: can't find referenced class com.actionbarsherlock.BuildConfig

Downloading the .zip and replacing the contents on the already configured module works fine. Which makes sense, the BuildConfig will be generated during the build process for the ActionBarSherlock module. But the .aar does not include the `BuildConfig` file, thus resulting on the error above.

Am I really the only one with this issue or the only one which tested this new .aar version with ProGuard?﻿

**Comment by JakeWharton** [comment]
> the only one which tested this new .aar version with ProGuard?﻿

Probably this one :)

**Comment by niqo01** [comment]
<- This one too ^^. Same error. Easy to fix when recompiling ourselves though.

**Comment by niqo01** [comment]
An easy hack while waiting this to be solved is to create the following class manually:

```
package com.actionbarsherlock;

/**
 * Hack while waiting ABS to fix AAR issue.
 * https://github.com/JakeWharton/ActionBarSherlock/issues/1001
 **/
public class BuildConfig {

  public static final boolean DEBUG = <place here your package>.BuildConfig.DEBUG;
}
```

**Comment by rfgamaral** [comment]
Nice workaround @niqo01.

I've looked at ABS code and it seems that `BuildConfig.DEBUG` is only being used **once**. All other debug checking is using `ActionBarSherlock.DEBUG`. So it should be just a quick replace (and remove the BuildConfig import of course) to fix it.

**Comment by lexer** [comment]
@rfgamaral You can also disable this warning with this line as workaround till next release

-dontwarn com.actionbarsherlock.internal.**

**Comment by JakeWharton** [comment]
Was merged to `dev`. Will go out in the next release.

**Comment by seva-ask** [comment]
I'm very glad that this issue was fixed. Hope new release will be deployed soon.

**Comment by Kisty** [comment]
Still getting the same problem using the 4.4.0@aar version. The -dontwarn line @lexer recommended worked for me.

**Comment by ashughes** [comment]
I'm also still getting the proguard warning with the 4.4.0@aar version. The -dontwarn line worked for me as well (but it would be nice to not have to have it).

**Comment by jblack10101** [comment]
Yea, still happening for me with 4.4.0@aar as well.

**Comment by mcginty** [comment]
Also having this issue with 4.4.0@aar

**Comment by ghost** [comment]
Still looks like going with -dontwarn is the best solution.

**Comment by ksperling** [comment]
Any chance of releasing a 4.4.1 with the fix in it?

**Comment by kafyazilim** [comment]
adamsın lexer
