### ISSUE TITLE
indeterminate progress bar on <API11 unavailable

### ISSUE THREAD

**Issue by felixb** [JakeWharton/ActionBarSherlock#41]
showing the indeterminate progress bar in action bar does work only in >API11.

calling setProgressBarIndeterminateVisibility(true) on <=API10 does nothing at all.

**Comment by JakeWharton** [comment]
This is fixed in the dev branch. Will be released with 3.1.

---

Jake Wharton
http://about.me/jakewharton
On Jul 17, 2011 9:51 AM, "felixb" <
reply@reply.github.com>
wrote:

**Comment by JakeWharton** [comment]
3.1 release tonight will have this.

**Comment by felixb** [comment]
i'm running your current dev branch and i still have this issue on <=API10 devices.

**Comment by JakeWharton** [comment]
Have you looked at [this](https://github.com/JakeWharton/ActionBarSherlock/blob/master/samples/demos/src/com/actionbarsherlock/sample/demos/app/ActionBarIndeterminateProgress.java#files) sample? I can confirm it works on 1.6, 2.3.3, and 3.2. You have to use `Boolean.TRUE` and `Boolean.FALSE` objects since `setProgressBarIndeterminateVisibility(boolean)` cannot be overridden.

**Comment by felixb** [comment]
ok thx. it's working.
