### ISSUE TITLE
Why artefact in maven repo contain android-support-v4.jar?

### ISSUE THREAD

**Issue by tprochazka** [JakeWharton/ActionBarSherlock#585]
Is is bug?
Or simply limitation of maven android plugin?

**Comment by JakeWharton** [comment]
It's a required dependency of the library. You can exclude it using the `<exclusions>` tag under your `<dependency>` declaration.

**Comment by tprochazka** [comment]
I know that it is required dependency, but it is not usual to pack depency directly to the artifact in maven world.
I mean this http://search.maven.org/remotecontent?filepath=com/actionbarsherlock/library/4.1.0/library-4.1.0.apklib
This zip directly contain libs\android-support-v4.jar
And this dependency should be resolved by maven.
So it is not possible to exlclude it via maven <exclusions> ;-)

**Comment by JakeWharton** [comment]
Ah, sorry. I misunderstood what you mean. This was fixed by #528 for the next release.

**Comment by peplin** [comment]
I think this is mostly a limitation with m2e-android, but I'm still having problems with this .jar file when using the m2e-android plugin. The problem is that the `nativeLibrariesDirectory` doesn't stop the .jar in `libs` from being added to the "Android Dependencies" section of the ABS project. This eventually causes an "already added" exception because both `android-support-v4.jar` (from libs) and `support-v4-r7.jar` from the pom.xml are added.

I'm going to file an issue in m2e-android and see what they think, but if anyone else runs into this issue, the workaround is to just delete the .jar from `actionbarsherlock/library/libs`.
